### ISSUE TITLE
预览编译不过messageNotification

### ISSUE THREAD

**Issue by cyourai** [netease-im/NIM_Web_Weapp_Demo#14]
提示
Error: 缺少文件, error: partials/messageNotification/messageNotification.js, file not found

**Comment by cyourai** [comment]
大小写

**Comment by andyzys** [comment]
@cyourai 目测是你本地的仓库之前拉过我们的代码，没有大小写敏感，你这边最快的解决办法是删除之前的老的仓库从新拉过，或者是你手动git rm过
