### ISSUE TITLE
更换自己的appkey后报错

### ISSUE THREAD

**Issue by jwaterwater** [netease-im/NIM_Web_Weapp_Demo#16]
{message: "事件服务解包失败", code: "事件服务解包失败", timetag: 1543849705330, event: "EVENT_SERVICE_ERROR", callFunc: null}
![image](https://user-images.githubusercontent.com/8943331/49382114-7d834780-f750-11e8-82af-fcd16a682ac5.png)

**Comment by andyzys** [comment]
@jwaterwater 请联系我们的技术支持获取更更多帮助，目测是你服务没开全
