### ISSUE TITLE
测试账号失效，无法进行登录

### ISSUE THREAD

**Issue by Adolf-L** [netease-im/NIM_Web_Weapp_Demo#17]
<img width="1629" alt="11" src="https://user-images.githubusercontent.com/10137107/50294701-6adb7300-04b1-11e9-92ef-1af8421d8d1c.png">
这个是什么情况呢？

**Comment by wuyuanaaa** [comment]
000-999 意思是 000 001 002 。。。 999

**Comment by Adolf-L** [comment]
> 000-999 意思是 000 001 002 。。。 999

这个是账号吗？

**Comment by ladyrank** [comment]
> > 000-999 意思是 000 001 002 。。。 999
> 
> 这个是账号吗？

是啊，哥，密码是 123456
