### ISSUE TITLE
重新加载后,就没有以前的会话消息了

### ISSUE THREAD

**Issue by aa992131860aa** [netease-im/NIM_Web_Weapp_Demo#18]

**Comment by aa992131860aa** [comment]
小程序重新加载后,就没有以前的会话消息了

**Comment by andyzys** [comment]
@aa992131860aa 是的，目前没做缓存，如有需要，暂时请自行实现

**Comment by aa992131860aa** [comment]
demo上面,重新编译后,还有最近的会话内容,但是放在我的小程序里面,就没有了,其他是正常的

**Comment by aa992131860aa** [comment]
@andyzys  demo上面,重新编译后,还有最近的会话内容,但是放在我的小程序里面,就没有了,其他是正常的
