### ISSUE TITLE
建议把相应的request合法域名和socket合法域名说明出来，配置了三次才完全配置好

### ISSUE THREAD

**Issue by dzeze** [netease-im/NIM_Web_Weapp_Demo#2]
request合法域名：
https://dr.netease.im
https://lbs.netease.im
https://wlnimsc0.netease.im
socket合法域名：
wss://wlnimsc0.netease.im
wss://app.netease.im

**Comment by www-wwj** [comment]
谢谢你的建议，我们会改进。不过socket域名会动态分配，跟技术支持确认下你们app的分配地址池，后续我们也会调整给出确定分配域名池，不再需要跟确认域名环节。

**Comment by www-wwj** [comment]
已更新
