### ISSUE TITLE
taro可以集成云信么，具体方法是什么

### ISSUE THREAD

**Issue by iamyang1314** [netease-im/NIM_Web_Weapp_Demo#23]

**Comment by Claiyre** [comment]
可以参考[云信开发手册](https://dev.yunxin.163.com/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/Web%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F)，引入SDK - SDK引入方式
