### ISSUE TITLE
socket重连机制

### ISSUE THREAD

**Issue by luckyinghai** [netease-im/NIM_Web_Weapp_Demo#25]
小程序从后台进入前台时，socket重接机制没有重新连接，导致其他人发来的消息收不到的

**Comment by eynol** [comment]
重连机制是有的，微信有一个app.json配置参数，可以参考这里[音视频通话 > SDK开发集成 > 小程序开发集成 > 集成方式](https://dev.yunxin.163.com/docs/product/%E9%9F%B3%E8%A7%86%E9%A2%91%E9%80%9A%E8%AF%9D/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F) 配置socket的连接时长 ,改小一点
