### ISSUE TITLE
强烈要求出个结合小程序框架mpvue、wepy写个demo！！！现在谁还用原生写？

### ISSUE THREAD

**Issue by KePingHub** [netease-im/NIM_Web_Weapp_Demo#31]

**Comment by eynol** [comment]
这个DEMO是展示接口如何处理的，作用是参考接口的使用。
看懂原生的用法，可以较快迁移到其他框架上，而且mpvue等等的框架挺多的，总不可能每出一个框架，demo就用新框架写一遍吧~
