### ISSUE TITLE
群聊

### ISSUE THREAD

**Issue by zombieEnginner** [netease-im/NIM_Web_Weapp_Demo#4]
群聊功能啥时候出来啊？

**Comment by jj89757hhb** [comment]
为什么把本地图标转换成base64来读取？

**Comment by andyzys** [comment]
@jj89757hhb 因为需要一些小图标，每个图标大小也就十Byte左右，假如所有图标封到一张sprite里面也不到1k，为了减少网络请求，所以转了base64

**Comment by zhongdaiqi** [comment]
@zombieEnginner 群聊功能我已经实现一版，直接在官方的基础上实现的

**Comment by andyzys** [comment]
已出
