### ISSUE TITLE
登录注册不了

### ISSUE THREAD

**Issue by hwyyy** [netease-im/NIM_Web_Weapp_Demo#6]
一直显示账号或密码错误

**Comment by Lucio0O** [comment]
你好，请问帐号密码是在Demo里注册的吗

**Comment by hwyyy** [comment]
是的 之前有注册过一次 是可以的 后面再登录 登录不了 想说可能是因为自己忘记了密码 再想注册  注册也注册不了了

**Comment by Lucio0O** [comment]
我试了下线上应该是可以注册的，你那边注册不了是什么提示？
