### ISSUE TITLE
通过userID跟token注测的 聊天列表页想获取到好友的nick 就是昵称怎么获取

### ISSUE THREAD

**Issue by hwyyy** [netease-im/NIM_Web_Weapp_Demo#7]
请问你的账号是通过注册页注册后无法登录吗？

**Comment by andyzys** [comment]
@hwyyy 请问你的账号是通过注册页注册后无法登录吗？

**Comment by andyzys** [comment]
@hwyyy 账号体系需要服务端自己去实现，可以借鉴我们DEMO的服务器端逻辑

**Comment by zhongdaiqi** [comment]
@hwyyy  获取nick，可以参考官方的chating页面，直接能获取到的。
