### ISSUE TITLE
为什么 imeventhandler.js 文件一直显示 globalData 未定义？

### ISSUE THREAD

**Issue by hwyyy** [netease-im/NIM_Web_Weapp_Demo#8]

**Comment by hwyyy** [comment]
解决了 是因为安卓跟IOS的新旧版的冲突没有解决

**Comment by hwyyy** [comment]
在 app.js 下调用imeventhandler.js  会显示 imeventhandler.js 的globalData 未定义

**Comment by zhongdaiqi** [comment]
不能这么使用！官方提供的demo与微信集成存在巨大的app生命周期控制问题！所以需要进行大的改造~

**Comment by andyzys** [comment]
@Lancker 你好，请问存在何“app生命周期控制问题”，具体指的是哪方便？目前来说，由于服务器返回数据是异步的，外加页面中消息订阅器以及微信页面生命周期，三者配合起来，可能会存在某些临界情况，需要特殊处理

**Comment by zhongdaiqi** [comment]
我已经集成好了，群聊也搞定了。你的问题是，app.js下调用imeventandler.js，是不能直接使用官方的代码的，要调整，要将app当成一个上下文传到imeventandler中，而不是直接在里面使用getapp，因此那个时候globalData本身是没有初始化好的。

**Comment by andyzys** [comment]
@Lancker 
1. DEMO中并没有在app.js下调用了imeventandler.js
2. imeventandler是处理im相关回调的中枢，整体是在login/register时初始化实例，然后存储在全局，请问这imeventandler中不能直接使用getApp是何意思?

**Comment by zhongdaiqi** [comment]
@andyzys demo做为独立的显示是没有问题，像我们集成云通信的使用场景，肯定不会像demo那么玩的！因此，当小程序打开的时候，我们都需要在app.js里完成消息通道的建立。因此，我从实践的角度推测出 @hwyyy 遇到的问题是在做集成调整的时候遇到了此问题。  你也可以想想，如果是你来做云通信集成，你会像demo那样子，搞一个登陆界面输入帐号密码？

**Comment by hwyyy** [comment]
@Lancker 是的 你推测的完全正确，之所以globalData 未定义 就是那时候还未初始化，后面将方法写在app.js 里面就能小程序全局调用了 我想请问一下 你的app 当成一个上下文传到imeventandler 是怎么实现的  ？怎么才能把他当成一个上下文？然后还能用到全局里面

**Comment by zhongdaiqi** [comment]
@hwyyy 等一下，我处理一下代码，把相关的代码提交到上来，你到我fork的代码库里去获取就好了。

**Comment by andyzys** [comment]
@Lancker @hwyyy 
App() 函数是用来注册一个小程序，生成全局app实例，你在此处初始化我们的IM连接实例（实例需要挂载在app.globalData中），这样肯定会造成循环引用，导致undefined。当初设计的时候是不推荐在此处进行IM的初始化操作(DEMO中登录页面仅仅是收集用户账户信息，并不代表你们真实需求中也一定要引入了该页，才能完成初始化)，你可以将**初始化IM连接实例在你们小程序的首页**执行即可（账号信息没必要登录页填写，相信你们初始化的环境下可以拿到）

`new IMEventHandler({ 
      token: MD5(password), 
      account: account 
    })`

你们的需求致使你们代码一定要在app.js中完成消息通道的建立吗？这有点类似于微信文档中说的 

> 不要在 onLaunch 的时候调用 getCurrentPages()，此时 page 还没有生成。

但是你非要在onlaunch中调用getCurrentPages()，于是你想尽办法如何在onLaunch中拿到页面栈，这本身就是互斥的。希望对你们有所帮助

**Comment by zhongdaiqi** [comment]
@Lancker @hwyyy  必须放在app中完成信息通道的建立的，小程序的入口可不一定是首页，小伙伴可能通过任何一个分享页进到小程序的!按你的思路在首页执行，跟实际的需求是违背的。 我已经解决了问题，实现了在app.js中完成信息通道的建立~~~  简单的来讲，把app注入到IMEventHandler中，而不是在IMEventHandler使用getapp，这样子就解决了问题。
在app.js中这么写：
`new IMEventHandler({ token: MD5(password), account: account,app:app,onsyncdone:function(){} })`
在IMEventHandler进行改造，基本上是将代码重组一下。即app使用注入进来的app，而不是自己去get。

**Comment by andyzys** [comment]
@Lancker 好的，多谢提醒，后面DEMO版本更新的时候会考虑你这个应用场景，尽量减少接入成本
